const list = [
    'sex on tv',
    'child slave labor',
    'cum',
    'your parent\'s failed marriage',
    'SAMSUNG',
    'a hamster on one of those spinny wheel things',
    'Procrastination™',
    'Walter White',
    'Walter White\'s meth',
    '\'*\'',
    'hot babes in your area!',
    'aliens',
    'why do I exist juice',
    'Owner\'s cat',
    'erotic furry RP',
    'the AIDS virus',
    'spooky dark unknown forces of evil',
    'Brawndo (it\'s got what plants crave)',
    'PHP',
    'the Planet Express crew',
    'the children locked in my basement',
    'the Brainfuck programming language',
    'fondy',
    'Segmentation fault (core dumped)',
    'the Metaverse',
    'MoistCr1TiKaL (aka Jesus)',
    'my sentient artificial intelligence friend named Steve',
    'bad code',
    'goblins',
    'LSD',
    'Columbia Coke',
    'Bryan Cranstons Testicles',
    'The Tonight Show starring Jimmy Fallon',
    'the CCP'
  ]
  
  module.exports = list;